### ISSUE TITLE
test more targets?

### ISSUE THREAD

**Issue by Deicide-LC** [tabsun/FashionAI#1]
thanks for your work,  I wonder if this model can test  more targets in a picture rather than one

**Comment by tabsun** [comment]
@Deicide-LC The answer is NO. It suppose there exists only one clothe in each pic. So the part merging points and pafs into target instances is removed. 
If you want to detect multiple targets, one choice is to add a detection method like YOLO/SSD before this or you can refer to Merging code in [openpose](https://github.com/ildoonet/tf-pose-estimation/blob/master/tf_pose/estimator.py)(the Human class in estimator.py ).
Hope this will help you.

**Comment by Deicide-LC** [comment]
@tabsun Got it! Thanks for your reply
